joint_names: [base_link1_joint, base_link2_joint]

joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

## velocity controller
joint_group_position_controller:
  type: position_controllers/JointGroupPositionController
  joints:
    - base_link1_joint
    - base_link2_joint
  required_drive_mode: 1

base_link1_joint_position_controller:
  type: position_controllers/JointPositionController
  joint: base_link1_joint
  required_drive_mode: 1

base_link2_joint_position_controller:
  type: position_controllers/JointPositionController
  joint: base_link2_joint
  required_drive_mode: 1
